#!/usr/bin/python
from httplib import HTTPSConnection, HTTPException
import socket
import ssl
import base64
import json

from gnt_rapi import GntRapi, GntTagMap

def gnt_tag_info(rapi_data,name,info_type):
	rapi=GntRapi(rapi_data["host"],rapi_data["port"],rapi_data["user"],
		rapi_data["pass"])

	tags_raw=rapi.query(["tags"],["=","name",name], # fields, filter
		qtype=info_type)["data"][0][0][1] # inst or net)[... parsing ...]

	tagmap=GntTagMap(tags_raw)
	return tagmap.dump()["ganeti_tags"]

def main():
	module=AnsibleModule(
		argument_spec={"rapi":{"required":True,"type":'dict'},
			"name":{"required":True,"type":'str'},
			"type":{"default":"instance","choices":["instance","network"]}},
		check_invalid_arguments=True,
		supports_check_mode=False)
	try:
		tag_info=gnt_tag_info(module.params['rapi'],module.params['name'],
			module.params["type"])
	except HTTPException as e:
		module.fail_json(msg="HTTP error: %s " % e)
	except socket.error as e:
		module.fail_json(msg="HTTP Socket error: %s" %e)
	except Exception as e:
		module.fail_json(msg="Error: %s " % e)
	else:
		module.exit_json(msg="Host fetched",changed=False,
			ansible_facts={"ganeti_tags":tag_info})

from ansible.module_utils.basic import *
if __name__ == '__main__':
	main()
